services:
  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
    ports:
      - "53306:3306"
volumes:
  database-data: